DROP TABLE IF EXISTS "Settings";


CREATE TABLE IF NOT EXISTS "Settings"
(
  Settings_id SERIAL PRIMARY KEY,
  Version INTEGER NOT NULL,
  Language VARCHAR(64) NOT NULL,
  Other_Settings INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "User"
(
  User_id SERIAL PRIMARY KEY,
  Email VARCHAR(64) NOT NULL,
  Login VARCHAR(64) NOT NULL,
	Settings_id INTEGER NOT NULL,
  Password VARCHAR(64) NOT NULL,
  FOREIGN KEY (Settings_id) REFERENCES "Settings" (Settings_id) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS "List"
(
  List_id SERIAL PRIMARY KEY,
  Name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS User_List
(
  User_List_id SERIAL PRIMARY KEY,
	User_id INTEGER NOT NULL,
	List_id INTEGER NOT NULL,
  FOREIGN KEY (User_id) REFERENCES "User" (User_id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (List_id) REFERENCES "List" (List_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Product
(
  Product_id SERIAL PRIMARY KEY,
  Name VARCHAR(64) NOT NULL,
  Colour VARCHAR(64) NOT NULL,
  Quantity INTEGER NOT NULL,
  Status VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS List_Product
(
  List_Product_id SERIAL PRIMARY KEY,
	Product_id INTEGER NOT NULL,
	List_id INTEGER NOT NULL,
  FOREIGN KEY (Product_id) REFERENCES Product (Product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (List_id) REFERENCES "List" (List_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Category"
(
  Category_id SERIAL PRIMARY KEY,
  Name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Product_Category
(
  Product_Category_id SERIAL PRIMARY KEY,
	Product_id INTEGER NOT NULL,
	Category_id INTEGER NOT NULL,
  FOREIGN KEY (Product_id) REFERENCES Product (Product_id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Category_id) REFERENCES "Category" (Category_id) ON DELETE CASCADE ON UPDATE CASCADE
);