DELETE FROM product_category WHERE TRUE;
DELETE FROM list_product WHERE TRUE;
DELETE FROM user_list WHERE TRUE;
DELETE FROM "Category" WHERE TRUE;
DELETE FROM Product WHERE TRUE;
DELETE FROM "List" WHERE TRUE;
DELETE FROM "User" WHERE TRUE;
DELETE FROM "Settings" WHERE TRUE
